version: "3.7"

services:
  ignite-challenge-database-queries:
    image: postgres
    container_name: ignite-challenge-database-queries
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ignite
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
